# Site settings
title: Hizli Cars
email: info@hizli-cars.com
description: > # this means to ignore newlines until "baseurl:"
  Location de voitures à Rabat - Salé - Casablanca
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude:
    - README.txt
